# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.define "vm1" do |vm1|
    vm1.vm.box = "debian/bookworm64"
    vm1.vm.hostname = "public-web"
    vm1.vm.network  "public_network"
    vm1.vm.synced_folder ".", "/vagrant_data"
    vm1.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y nginx
      echo "Hello I'm VM1" > /vagrant_data/HelloVM1.txt
    SHELL
  end
  config.vm.define "vm2" do |vm2|
    vm2.vm.box = "debian/bookworm64" 
    vm2.vm.hostname = "private-server" 
    vm2.vm.network "private_network", ip: "192.168.87.3"
    vm2.vm.synced_folder ".", "/vagrant_data"
    vm2.vm.provision "shell", path: "provision_vm2.sh"
  end
    config.vm.define "vm3" do |vm3|
    vm3.vm.box = "debian/bookworm64" 
    vm3.vm.hostname = "public-server-static-ip" 
    vm3.vm.network "public_network", ip: "[YOUR_IP]", bridge: "[YOUR_ADAPTER]"
    vm3.vm.synced_folder "shared", "/vagrant_data"
    vm3.vm.provision "shell", path: "provision_vm3.sh"
  end
end
